# @package _global_
model:
  # T2T-ViT 7
  _target_: src.models.vit.t2t_vit.T2T_ViT
  # TODO: check the qk_scale
  tokens_type: transformer
  embed_dim: 256
  depth: 7
  num_heads: 4
  mlp_ratio: 2.0
