_target_: src.models.modules.layers.mlp.MlpCustom
linear1_cfg:
  _target_: src.models.modules.layers.fastlinear.SparseLRLinear
  rank: 0.05
  sparse_cfg:
    _target_: src.models.modules.layers.blocksparse_linear.ButterflyBlockdiagLinear
    nblocks: 16
linear2_cfg: ${.linear1_cfg}
